/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./AboutSection.module.css"; 
import AboutMe from "./AboutMe";
import SocialFooter from "./SocialFooter";

const AboutSection = () => {
  return (
    <section id="aboutSection" className={styles.aboutSection}>
      <div className={styles.container}>
        <main className={styles.mainContent}>
          <AboutMe />
        <SocialFooter />
        </main>
      </div>
    </section>
  );
};

export default AboutSection;
